In [3]:
import numpy as np

import pandas as pd

import xarray as xr

In [4]:
xr.DataArray(np.random.randn(2, 3))

<xarray.DataArray (dim_0: 2, dim_1: 3)>
array([[-0.671362,  1.073866, -2.498546],
       [ 0.007044,  0.204265, -1.543709]])
Dimensions without coordinates: dim_0, dim_1

In [5]:
data = xr.DataArray(np.random.randn(2, 3), coords={'x': ['a', 'b']}, dims=('x', 'y'))

In [6]:
data

<xarray.DataArray (x: 2, y: 3)>
array([[ 1.451615,  0.866997,  0.602571],
       [-0.125315, -1.160773, -0.944568]])
Coordinates:
  * x        (x) <U1 'a' 'b'
Dimensions without coordinates: y

In [7]:
data.values

array([[ 1.45161461,  0.86699736,  0.60257077],
       [-0.12531528, -1.16077273, -0.94456802]])

In [8]:
data.dims

('x', 'y')

In [9]:
data.coords

Coordinates:
  * x        (x) <U1 'a' 'b'

In [10]:
data.attrs

OrderedDict()

In [11]:
data[[0, 1]]

<xarray.DataArray (x: 2, y: 3)>
array([[ 1.451615,  0.866997,  0.602571],
       [-0.125315, -1.160773, -0.944568]])
Coordinates:
  * x        (x) <U1 'a' 'b'
Dimensions without coordinates: y

In [12]:
data.loc['a':'b']

<xarray.DataArray (x: 2, y: 3)>
array([[ 1.451615,  0.866997,  0.602571],
       [-0.125315, -1.160773, -0.944568]])
Coordinates:
  * x        (x) <U1 'a' 'b'
Dimensions without coordinates: y

In [14]:
data.isel(x=slice(2))

<xarray.DataArray (x: 2, y: 3)>
array([[ 1.451615,  0.866997,  0.602571],
       [-0.125315, -1.160773, -0.944568]])
Coordinates:
  * x        (x) <U1 'a' 'b'
Dimensions without coordinates: y

In [16]:
data + 10

<xarray.DataArray (x: 2, y: 3)>
array([[11.451615, 10.866997, 10.602571],
       [ 9.874685,  8.839227,  9.055432]])
Coordinates:
  * x        (x) <U1 'a' 'b'
Dimensions without coordinates: y

In [17]:
np.sin(data)

<xarray.DataArray (x: 2, y: 3)>
array([[ 0.992906,  0.762389,  0.566762],
       [-0.124988, -0.917111, -0.810244]])
Coordinates:
  * x        (x) <U1 'a' 'b'
Dimensions without coordinates: y

In [18]:
data.T

<xarray.DataArray (y: 3, x: 2)>
array([[ 1.451615, -0.125315],
       [ 0.866997, -1.160773],
       [ 0.602571, -0.944568]])
Coordinates:
  * x        (x) <U1 'a' 'b'
Dimensions without coordinates: y

In [19]:
data.sum()

<xarray.DataArray ()>
array(0.690527)